# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    env:
      STORAGE_DOMAIN: ${{secrets.STORAGE_DOMAIN}}
      SUB_DIRECTORY: ${{secrets.SUB_DIRECTORY}}
      NEXT_PUBLIC_STORAGE_DOMAIN: ${{secrets.STORAGE_DOMAIN}}
      NEXT_PUBLIC_SPACE_ID: ${{secrets.SPACE_ID}}
      NEXT_PUBLIC_DELIVERY_ACCESS_TOKEN: ${{secrets.DELIVERY_ACCESS_TOKEN}}
      NEXT_PUBLIC_CONTENT_TYPE_ID: ${{secrets.CONTENT_TYPE_ID}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn build

      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: out
          destination: ${{ secrets.bucket_name }}
          parent: false
